### PR TITLE
Add text sharing functions

### PR DESCRIPTION
**Pull request by obar**
I found the clipboard sharing to thrash both my computer and cell clipboards with contents I didn't need, so explicitly using `--share-text` seemed like a good idea. I hope this contribution fits with your elegant package here!

### CODE REVIEW

**Comment by carldotac** [comment]
Thank you! This is very cool functionality. Awesome that it would help your workflow.

Once I have a moment I'll test and look more closely and then I can merge it in. It'd be a great addition to the package.

**Comment by obar** [comment]
Great.

I just realized the interactive helper was a little more complicated than needed (I was going to provide feedback in the "send the region" case but realized later the shell-command output works fine for this), so I'll take out the logic inversion and force-push in a minute. The functionality is unchanged.

**Comment by carldotac** [comment]
Looks good to me. Merged. Thanks again for your contribution!

**Comment by obar** [comment]
As you saw there isn't much to what I added :) Thank *you* for the package, it made it very easy for me to get where I wanted!

**Pull request merged**
